language: node_js
node_js:
  - "8"

install:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_JOB_NUMBER
  - git log -1 --pretty=oneline

before_script:
  - npm install -g gulp-cli
  - npm install jsonfile

script:
- bash deploy.sh
